name: build_and_unit_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        path: go/src/github.com/GreengageDB/gpbackup-s3-plugin

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.23"

    - name: Set Environment
      run: |
        echo "GOPATH=/home/runner/work/gpbackup-s3-plugin/gpbackup-s3-plugin/go" >> $GITHUB_ENV
        echo "/home/runner/work/gpbackup-s3-plugin/gpbackup-s3-plugin/go/bin" >> $GITHUB_PATH

    - name: Dependencies
      run: |
        cd ${GOPATH}/src/github.com/GreengageDB/gpbackup-s3-plugin
        make depend

    - name: Build
      run: |
        cd ${GOPATH}/src/github.com/GreengageDB/gpbackup-s3-plugin
        make build

    - name: Unit Test
      run: |
        cd ${GOPATH}/src/github.com/GreengageDB/gpbackup-s3-plugin
        make test
